version: '3'

services:
    postgres:
        image: postgres:latest
        container_name: locklite-postgresql
        ports:
            - "${POSTGRES_PORT}:5432"
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}
        volumes:
            - locklite-postgresql-vol:/var/lib/postgresql/data

volumes:
    locklite-postgresql-vol:
